
# Define trigger type actions in higher layer configs in this table.
# Require keys for per key: InputName.
# You can bind more than one InputName to an action.
# for example:
#   [[InputTriggerActions.MoveForward]]
#   InputName = "KEY_W"
#	InputMode = "KEY_PRESS"
#   [[InputTriggerActions.MoveForward]]
#   InputName = "KEY_UP"
[InputTriggerActions]

# Define axis actions in higher layer configs in this table.
# Require keys for per key: InputName, Scale.
# You can bind more than one InputName to an action.
# for example:
#   [[InputAxisActions.Pitch]]
#   InputName = "MOUSE_X"
#	InputMode = "KEY_PRESS"
#   Scale = 1.0
[InputAxisActions]